### ISSUE TITLE
Installation issue - 'npm install --production' giving error

### ISSUE THREAD

**Issue by saadaan** [enketo/enketo-express#244]
Hi,

Trying to install enketo express. Getting following errors in the steps: 

```
enketo@ip-172-31-12-238:~/enketo-express$ sudo npm install --production
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'enketo-express@2.6.3',
npm WARN EBADENGINE   required: { node: '>=12', npm: '>=6 <7' },
npm WARN EBADENGINE   current: { node: 'v12.21.0', npm: '7.6.3' }
npm WARN EBADENGINE }
npm ERR! code 1
npm ERR! path /home/enketo/enketo-express/node_modules/libxslt
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! make: Entering directory '/home/enketo/enketo-express/node_modules/libxslt/build'
npm ERR!   CC(target) Release/obj.target/libexslt/deps/libxslt/libexslt/common.o
npm ERR!   CC(target) Release/obj.target/libexslt/deps/libxslt/libexslt/crypto.o
npm ERR!   CC(target) Release/obj.target/libexslt/deps/libxslt/libexslt/date.o
npm ERR!   CC(target) Release/obj.target/libexslt/deps/libxslt/libexslt/dynamic.o
npm ERR!   CC(target) Release/obj.target/libexslt/deps/libxslt/libexslt/exslt.o
npm ERR!   CC(target) Release/obj.target/libexslt/deps/libxslt/libexslt/functions.o
npm ERR!   CC(target) Release/obj.target/libexslt/deps/libxslt/libexslt/math.o
npm ERR!   CC(target) Release/obj.target/libexslt/deps/libxslt/libexslt/saxon.o
.
.
.
.
npm ERR!    vasprintf(&message, msg, args);
npm ERR!    ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
npm ERR! g++: error: /home/enketo/enketo-express/node_modules/node1-libxmljsmt/build/Release/xmljs.node: No such file or directory
npm ERR! make: *** [Release/obj.target/node-libxslt.node] Error 1
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/home/enketo/enketo-express/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
npm ERR! gyp ERR! System Linux 5.4.0-1038-aws
npm ERR! gyp ERR! command "/usr/bin/node" "/home/enketo/enketo-express/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /home/enketo/enketo-express/node_modules/libxslt
npm ERR! gyp ERR! node -v v12.21.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/enketo/.npm/_logs/2021-03-19T21_51_41_838Z-debug.log
```

Can someone kindly help? Thanks!

**Comment by MartijnR** [comment]
use npm 6 https://github.com/enketo/enketo-express/issues/240

**Comment by saadaan** [comment]
Hi @MartijnR,

I tried npm 6. But still installation is not working. Here is the log snapshot:

```
17886 verbose pkgid node1-libxmljsmt@1.0.0
17887 verbose cwd /home/enketo/enketo-express
17888 verbose Linux 5.4.0-1038-aws
17889 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "--production"
17890 verbose node v12.21.0
17891 verbose npm  v6.14.11
17892 error code ELIFECYCLE
17893 error errno 1
17894 error node1-libxmljsmt@1.0.0 install: `node-pre-gyp install --fallback-to-build --loglevel http`
17894 error Exit status 1
17895 error Failed at the node1-libxmljsmt@1.0.0 install script.
17895 error This is probably not a problem with npm. There is likely additional logging output above.
17896 verbose exit [ 1, true ]
```

Let me know if you can suggest anything. I am following exact commands given on https://blog.enketo.org/install-enketo-production-ubuntu/

Thanks,
Saad

**Comment by saadaan** [comment]
This is on the command prompt:

```
# npm install --production

> node1-libxmljsmt@1.0.0 install /home/enketo/enketo-express/node_modules/node1-libxmljsmt
> node-pre-gyp install --fallback-to-build --loglevel http

node-pre-gyp ERR! Pre-built binaries not installable for node1-libxmljsmt@1.0.0 and node@12.21.0 (node-v72 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Hit error EACCES: permission denied, mkdir '/home/enketo/enketo-express/node_modules/node1-libxmljsmt/build'
gyp WARN EACCES current user ("ubuntu") does not have permission to access the dev dir "/root/.cache/node-gyp/12.21.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/enketo/enketo-express/node_modules/node1-libxmljsmt/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/enketo/enketo-express/node_modules/node1-libxmljsmt/.node-gyp'
gyp ERR! System Linux 5.4.0-1038-aws
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--loglevel=http" "--module=/home/enketo/enketo-express/node_modules/node1-libxmljsmt/build/Release/xmljs.node" "--module_name=xmljs" "--module_path=/home/enketo/enketo-express/node_modules/node1-libxmljsmt/build/Release" "--napi_version=7" "--node_abi_napi=napi"
gyp ERR! cwd /home/enketo/enketo-express/node_modules/node1-libxmljsmt
gyp ERR! node -v v12.21.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --loglevel=http --module=/home/enketo/enketo-express/node_modules/node1-libxmljsmt/build/Release/xmljs.node --module_name=xmljs --module_path=/home/enketo/enketo-express/node_modules/node1-libxmljsmt/build/Release --napi_version=7 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/enketo/enketo-express/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1022:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
node-pre-gyp ERR! System Linux 5.4.0-1038-aws
node-pre-gyp ERR! command "/usr/bin/node" "/home/enketo/enketo-express/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--loglevel" "http"
node-pre-gyp ERR! cwd /home/enketo/enketo-express/node_modules/node1-libxmljsmt
node-pre-gyp ERR! node -v v12.21.0
node-pre-gyp ERR! node-pre-gyp -v v0.9.1
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --loglevel=http --module=/home/enketo/enketo-express/node_modules/node1-libxmljsmt/build/Release/xmljs.node --module_name=xmljs --module_path=/home/enketo/enketo-express/node_modules/node1-libxmljsmt/build/Release --napi_version=7 --node_abi_napi=napi' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node1-libxmljsmt@1.0.0 install: `node-pre-gyp install --fallback-to-build --loglevel http`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node1-libxmljsmt@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-22T20_17_55_573Z-debug.log

```

**Comment by saadaan** [comment]
OK I have fixed it. It was OS permissions issue.
